export const initialValues = [
  { img: 'https://i.ibb.co/JsyPgGb/IMG-0685-2.webp', category: 'Love Story' },
  { img: 'https://i.ibb.co/LR0GSxm/IMG-0966.webp', category: 'Love Story' },
  { img: 'https://i.ibb.co/mzHjt9p/IMG-1031.webp', category: 'Love Story' },
  { img: 'https://i.ibb.co/LzwszP6/IMG-1026.webp', category: 'Love Story' },
  { img: 'https://i.ibb.co/1G21qzx/IMG-0879.webp', category: 'Love Story' },
  { img: 'https://i.ibb.co/qYV0zQ0/IMG-1214.webp', category: 'Love Story' },
  { img: 'https://i.ibb.co/wgFF7pW/IMG-1359.webp', category: 'Love Story' },
  { img: 'https://i.ibb.co/xhKdM7m/IMG-1419.webp', category: 'Love Story' },
  { img: 'https://i.ibb.co/9w1gRYC/IMG-0613.webp', category: 'Wedding Day' },
  { img: 'https://i.ibb.co/7Stf51g/IMG-0615.webp', category: 'Wedding Day' },
  { img: 'https://i.ibb.co/2Ps4kQL/IMG-0623.webp', category: 'Wedding Day' },
  { img: 'https://i.ibb.co/K7FzV65/IMG-0633.webp', category: 'Wedding Day' },
  { img: 'https://i.ibb.co/q71b1mG/IMG-0636.webp', category: 'Wedding Day' },
  { img: 'https://i.ibb.co/cg3vT6j/IMG-0653.webp', category: 'Wedding Day' },
  { img: 'https://i.ibb.co/D5SfB77/IMG-0656.webp', category: 'Wedding Day' },
  { img: 'https://i.ibb.co/41cvfzL/IMG-0660.webp', category: 'Wedding Day' },
  { img: 'https://i.ibb.co/cbc2pnN/IMG-0726.webp', category: 'Wedding Day' },
  { img: 'https://i.ibb.co/30tcsR0/IMG-0752.webp', category: 'Wedding Day' },
  { img: 'https://i.ibb.co/0KNks8x/IMG-0789.webp', category: 'Wedding Day' },
  { img: 'https://i.ibb.co/H4Xcxhd/IMG-3154.webp', category: 'Individual' },
  { img: 'https://i.ibb.co/9NpCQxN/IMG-3315.webp', category: 'Individual' },
  { img: 'https://i.ibb.co/0B8M2XZ/IMG-3204.webp', category: 'Individual' },
  { img: 'https://i.ibb.co/Kz5BRzC/IMG-3230.webp', category: 'Individual' },
  { img: 'https://i.ibb.co/cDK8jpG/IMG-3223.webp', category: 'Individual' },
  { img: 'https://i.ibb.co/ZVRfgPw/IMG-3363.webp', category: 'Individual' },
  { img: 'https://i.ibb.co/M1z015x/IMG-3343.webp', category: 'Individual' },
  { img: 'https://i.ibb.co/5rjzGrS/IMG-3196.webp', category: 'Individual' },
  { img: 'https://i.ibb.co/HddC1pj/IMG-3434.webp', category: 'Individual' },
];
